### ISSUE TITLE
How to create order from another smart contract?

### ISSUE THREAD

**Issue by artiya4u** [0xProject/0x-monorepo#1070]
I try to build mirror trading on 0x protocol.
User's token can be deposit to smart contract wallet and let us gain control of their fund.
Does it possible to create order on behalf of users since it needs to sign order from an actual wallet?

**Comment by fabioberger** [comment]
@artiya4u once a users funds are deposited to a smart contract, the contract can create orders on behalf of the user.

**Comment by artiya4u** [comment]
@fabioberger Can you provide an example?

**Comment by abandeali1** [comment]
Checkout the `examples` directory in the `contracts` package. Something like [this](https://github.com/0xProject/0x-monorepo/blob/development/packages/contracts/src/2.0.0/examples/Wallet/Wallet.sol) can be added to any wallet that holds a user's assets in order to allow that user to sign an order on the contract's behalf.

**Comment by artiya4u** [comment]
@abandeali1 Does it available on v2 only?
