### ISSUE TITLE
[order-watcher] Invalid params: unknown field `blockHash`  0x.js@1.0.6

### ISSUE THREAD

**Issue by amaurer** [0xProject/0x-monorepo#1119]
## Current Behavior

When running an instance of OrderWatcher (server side), the error below repeats every 200ms.

{ code: -32602,
  message: 'Invalid params: unknown field `blockHash`, expected one of `fromBlock`, `toBlock`, `address`, `topics`, `limit`.' }
{ code: -32602,
  message: 'Invalid params: unknown field `blockHash`, expected one of `fromBlock`, `toBlock`, `address`, `topics`, `limit`.' }
{ code: -32602,
  message: 'Invalid params: unknown field `blockHash`, expected one of `fromBlock`, `toBlock`, `address`, `topics`, `limit`.' }

Looking at the code, seems to be some RPC validation error.  I upgrade my full Parity instance and same issue.  

## Steps to Reproduce (for bugs)

```
1. Run orderwatcher on 0x.js@1.0.5 (server side)
2. View no errors
3. npm install 0x.js@1.0.6 
4. Run orderwatcher, view errors
```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.6  |
| `Exchange Contract` | v2      |
| `node` |  8.11.3      |
| `parity` |  v2.0.6|stable      |

| Network |
| ------- |
| mannet    |

**Comment by fabioberger** [comment]
@amaurer this is not a bug. Since version [2.0.0](https://github.com/0xProject/0x-monorepo/blob/development/packages/order-watcher/CHANGELOG.md#v200---september-25-2018) OrderWatcher now relies on the ability to fetch logs by `blockHash` proposed in [EIP234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md).

As stated in the changelogs, OrderWatcher must be used with a backing node with version: Geth > v1.8.13 and Parity > v2.1.0. Infura also works.
