### ISSUE TITLE
0x Automated Market Maker Kit

### ISSUE THREAD

**Issue by arikan** [0xProject/0x-monorepo#1522]
[Market making on 0x](https://0x.org/wiki#Market-Making-on-0x) has a number of technical challenges and nuances due to the required on-chain interactions. An easy-to-use "0x Automated Market Maker" kit would help grow the 0x open relay ecosystem. It could have the following features from a bird's-eye view:

- A market making strategy library or template system that allows use of a variety of strategies, possibility to easily switch between them, and a modular system where users can easily configure and the community can develop on top and add new strategies over time.

- Fundamental actions: [watching](https://0x.org/wiki#0x-OrderWatcher) and [batch cancelling orders](https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#cancelling-orders), and automatically [creating and posting new orders](https://0x.org/wiki#Find,-Submit,-Fill-Order-From-Relayer) according to the chosen strategy.

- Methods for querying or dynamically displaying the status of ask and bid orders / bands.

- Some sort of [an incentive](https://medium.com/@rzurrer/keepers-reboot-observations-forward-looking-trends-f0d3aae6d1c5) to run across open order books using Standard Relayer APIs.

- Well written readme, best practices, and tutorials for new market makers as many hodlers (small and medium portfolios) can benefit from automated market making. 

- Promotion of developing and sharing strategy templates (It would not be a conflict of interest between market makers due to the art of configuring strategies).

**Comment by benjyz** [comment]
MM algos require things like

* monitoring and storing orderbook
* transaction history, Profit-loss, reporting
* maintaining a server with a web-interface 
* a quantitative model/strategy
* test performance of a strategy (backtest/livetest)

The general opensource tooling for automated trading in general is in its infancy. Because MM typically maintain a large number of orders and execute a large number of transactions, MM is more demanding than a simple trading strategy.

The hard part of MM infrastructure is the need to write concurrent/async code in several threads, maintain a lot of data and needing to react in rather low latencies. 

MM professionals will want to trade on many exchanges at the same time. An MM framework ideally caters to not one liquidity pool, but the entire market. Something to possibly keep in mind for active MM traders looking at 0x protocol.

**Comment by mifeng** [comment]
We have partnered with 0x to build hummingbot.io, which should satisfy most of these requirements. It's an open tool that allows you to load configurable strategy templates and run automated MM bots across multiple exchanges. We plan to make it generally available by end of February.

**Comment by fabioberger** [comment]
@arikan we are also working on a 0x MM tool kit so stay tuned to hear more about this soon!
