### ISSUE TITLE
Recommended way of deploying sol-compiler artifacts

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-monorepo#1526]
Hello. I'm wondering what the recommended process is for deploying artifacts created by sol-compiler (Both to a development blockchain in docker with 0xorg/devnet as well as to production).

I think I'll need to write something similar to 0x-migrate. Is that the right path? I'm hoping for something that's easy to setup since I would prefer to spend time writing my actual contracts.

I've previously been using `truffle migrate` for my project, but truffle doesn't support compiling contracts with mixed versions so I think sol-compiler is what I want. I don't see a way to use sol-compiler's output with truffle's artifact helpers though.

I also don't really want to pay gas to setup and use Migrations.sol and would be fine keeping that information off chain. I think that would simplify any deployment code.

**Comment by LogvinovLeon** [comment]
Thanks for bringing it up @WyseNynja.

1. Truffle migrations.
I completely agree with you. We didn't like it either and didn't find the migration contract useful. It was also buggy at the time and had some race conditions (haven't checked in a while). We also sometimes wanted to have non-linear migrations and all sorts of customizations. Different migrations on different networks etc. While all of that could be possibly achieved with truffle migrations - it felt like the value we get from that system is rather negative.

2. Our current migrations (I specifically don't call it sol-compiler migrations)
It's a much less opinionated process and therefore it requires some setup. What we currently do lives [here](https://github.com/0xProject/0x-monorepo/tree/development/packages/migrations)
And specifically [here](https://github.com/0xProject/0x-monorepo/blob/development/packages/migrations/src/migration.ts) We first take the artifacts and use [abi-gen](https://blog.0xproject.com/abi-to-typescript-generator-b0fb5cae9e29) to generate the contract wrappers. `Abi-gen` needs [templates](https://github.com/0xProject/0x-monorepo/tree/development/packages/abi-gen-templates). You can either use them or modify them for your needs. The ones we have have `deploy()` and `deployFrom0xArtifacts()` functions. So they are not `sol-compiler` specific but are slightly easier to use with `sol-compiler`. Then we [store](https://github.com/0xProject/0x-monorepo/tree/development/packages/abi-gen-wrappers) them. You can find an example of the generated wrapper [here](https://github.com/0xProject/0x-monorepo/blob/development/packages/abi-gen-wrappers/src/generated-wrappers/weth9.ts). After that we run custom migration scripts like ones in the migrations folder and they use those generated wrappers. That allows us to be fully type-safe. Even when you pass constructor arguments.

Id does require some setup and understanding. You need to install abi-gen. Install templates. Run abi-gen. Write migrations. But the setup you get is super-flexible and has reasonable defaults. For example I would really recommend to start with our templates, because writing your own can be a time-sink.

**Comment by WyseNynja** [comment]
Now that #1579 is closed, I should be able to do this easily. I’ll make a blogpost or something. 

Thanks for the help!
