### ISSUE TITLE
Python Order Utilities: Requires storing your private key in a node

### ISSUE THREAD

**Issue by virtualmotion** [0xProject/0x-monorepo#1565]
It would be a significant security improvement if there was an option to pass in the private key as a parameter when signing orders -- as opposed to the current methodology of unlocking the key in the node and passing in the connection to the node with the key unlocked.

**Comment by feuGeneA** [comment]
I've slated this for discussion with the team at our Sprint Planning meeting on Monday.  It may or may not make it onto our next Sprint, depending on other priorities.

In the mean time, have you tried using web3.py to accomplish this?  While a convenience method in `0x-order-utils` does seem reasonable, it also doesn't seem too onerous to use web3.py directly.

See https://web3py.readthedocs.io/en/stable/web3.eth.account.html#sign-a-message .  Presumably you can use the output of `zero_ex.order_utils.generate_order_hash_hex()` for the `message_hash` parameter to `w3.eth.account.signHash()`.

Also, have you looked at [the source for `order_utils.sign_hash()`](http://0x-order-utils-py.s3-website-us-east-1.amazonaws.com/_modules/zero_ex/order_utils.html#sign_hash)?  It is not too complicated, and most of the logic in there is around verifying the signature, which depends on the order of the elliptic curve parameters, which in turn depends on the node implementation that handled the `eth.sign()` call.  But [that `w3.eth.account.signHash()` method returns an `AttributeDict`](https://eth-account.readthedocs.io/en/latest/eth_account.html#eth_account.account.Account.signHash), which identifies those curve parameters by name, so there's no ambiguity like there is with `eth.sign()`.  You should be able to use `order_utils.is_valid_signature()` to verify the output of `account.signHash()` if you first transform that `AttributeDict`  into a `v+r+s+t` signature format, like `order_utils.sign_hash()` does via `order_utils._convert_ec_signature_to_vrs_hex()`.

**Comment by virtualmotion** [comment]
I really think it's a bad idea to leave this in your codebase.  People get robbed all the time for the security setup it mandates.

https://cryptoslate.com/hackers-scoop-20-million-in-eth-from-exposed-ethereum-nodes/

You cannot use w3.eth.account.signHash() to sign the output of zero_ex.order_utils.generate_order_hash_hex().  The signature gets bounced.

I hear you on the last paragraph, it should work in theory, I've not gotten it working.

**Comment by fabioberger** [comment]
@virtualmotion, this is actually not the case. Our libraries simply expect that you pass in a provider that conforms to the [BaseProvider](https://github.com/ethereum/web3.py/blob/master/web3/providers/base.py) class provided by Web3.py. All their providers extend this class.

The `BaseProvider` class supports a [middleware stack](https://github.com/ethereum/web3.py/blob/0617444b243d878708997009869fe5fd67a57041/docs/internals.rst#middlewares) that can intercept JSON RPC requests, add pre/post-processing and even handle the request instead of passing it the backing Ethereum node. 

You could easily implement a middleware that intercepts all account-related requests and handles them locally instead of forwarding the request to an unlocked Ethereum node. This is actually exactly what we do in our [SignerSubprovider](https://github.com/0xProject/0x-monorepo/blob/development/packages/subproviders/src/subproviders/signer.ts#L45) class in the `@0x/subproviders` package. At a minimum you must handle the `eth_accounts`, `eth_sign`, `eth_signTypedData` JSON RPC requests.

We will try and get an example implementation into `contract-demo` package soon, but have other things that are keeping us busy at the moment.

**Comment by virtualmotion** [comment]
Okay, thank you for the middleware info.

**Comment by fabioberger** [comment]
No problem @virtualmotion! If you get it working, would be great if you could share your middleware implementation here for others to learn from :)
