### ISSUE TITLE
python: AssetData serialize

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#1605]
I run into a problem with serialization of the makerAssetData and takerAssetData field. a relayer returns that the fields are wrongly formatted, but its what the relayer itself returned.

`:[{"field":"makerAssetData","code":1001,"reason":"Incorrect format (Invalid value)"},{"field":"takerAssetData","code":1001,"reason":"Incorrect format (Invalid value)"}]}"
`

this assert requires assetdata to be string. assert_valid(order, "/orderSchema").

https://github.com/0xProject/0x-monorepo/blob/development/python-packages/order_utils/src/zero_ex/order_utils/__init__.py#L198

but then
```
File "/usr/local/lib/python3.6/site-packages/zero_ex/order_utils/init.py", line 199, in order_to_jsdict
    jsdict["makerAssetData"] = "0x" + order["makerAssetData"].hex()
AttributeError: 'str' object has no attribute 'hex'
```

see also 

https://github.com/makerdao/pymaker/blob/2fc3aa8ff853e4ccd2504d9f3bc2cb9a115dfab1/pymaker/zrxv2.py#L66

**Comment by feuGeneA** [comment]
[A Python `Order` object](http://0x-order-utils-py.s3-website-us-east-1.amazonaws.com/#zero_ex.order_utils.Order) that will be passed into the `Exchange` contract must have the asset data as a `bytes` object.  This is because the smart contract expects an instance of (Solidity) `bytes`, so therefore web3.py expects an instance of (Python) `bytes`.  If you pass the asset data as an instance of `bytes` rather than `str`, then that call to `hex()` will succeed.

Try using `bytes.fromhex(your_asset_data_hex_string)`.

Please re-open if this doesn't solve the problem for you.
