### ISSUE TITLE
how to fill an order on remix using fillOrder function of exchange smart contract after ?

### ISSUE THREAD

**Issue by abhisharma1357** [0xProject/0x-monorepo#1644]
## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

| Package | Version |
| ------: | :------ |

| Network |
| ------- |
| NAME    |

**Comment by dekz** [comment]
@abhisharma1357 are you deploying the contracts via remix? Or are you attempting to call the already deployed contracts on a test network via remix?

**Comment by abhisharma1357** [comment]
I have already deployed on rinkeby using remix now i want to fill order

**Comment by dekz** [comment]
@abhisharma1357 What are you trying to achieve? 0x is already deployed on Rinkeby. You'll need an order that has been generated off-chain, then once you have an order you can fill it via the contracts. 

I would recommend you follow the [0x-starter-project](https://github.com/0xProject/0x-starter-project/tree/master/src) rather than try and use Remix to fill orders.
