### ISSUE TITLE
sol-cov: Wrong coverage report when using compiler optimizer.

### ISSUE THREAD

**Issue by azavalla** [0xProject/0x-monorepo#1786]
When compiler optimizer is on, coverage report shows some lines RED even when those lines are covered by tests. For the moment, I'm using the `/* solcov ignore next */` flag to skip those lines, but it's obviously not an adequate solution.

## Expected Behavior
Source code lines that are covered by tests should be marked as _hit_ (GREEN) when solc optimizer is on.

![screenshot_230419-13 59 27](https://user-images.githubusercontent.com/7092991/56600939-4367f480-65d0-11e9-8eb1-30fb09e82c75.png)

## Current Behavior
Source code lines that are covered by tests are marked as _miss_ (RED) when solc optimizer is on.

![screenshot_230419-14 00 29](https://user-images.githubusercontent.com/7092991/56600960-4bc02f80-65d0-11e9-99fa-ac522a75d4de.png)

## Steps to Reproduce (for bugs)
Here's the [repository to reproduce](https://github.com/azavalla/repo-to-reproduce-sol-coverage-bug)

**Comment by azavalla** [comment]
:(

**Comment by fabioberger** [comment]
Sorry we haven't been able to fix this issue @azavalla. These types of issues are inherent to the way our coverage tool works. Since it's going through the bytecode and mapping them back to lines of source code, the optimizer can make this a lot harder. Sometimes after using the optimizer, there is literally no more link between the byte-code and certain lines of source. This is what's happening in your situation. We are unsure as to how this can be addressed.

**Comment by PaulRBerg** [comment]
FWIW, I solved this issue like this in `truffle-config.js`:

```
if (process.env.MODE) {
  truffleOptions.provider = provider;
  compilerSettings.optimizer.enabled = false;
} else {
  truffleOptions.host = "127.0.0.1";
  compilerSettings.optimizer.enabled = true;
}
```

Where the `MODE` environment variable indicated whether I'm running the coverage, profiling or tracing tool.
 
Check out the [whole source code](https://github.com/sablierhq/sablier/blob/develop/packages/protocol).
