### ISSUE TITLE
devnet: Is packages still maintained?

### ISSUE THREAD

**Issue by hoytech** [0xProject/0x-monorepo#1831]
I just tried to re-generate my coverage test report and fell down a rabbit-hole. I was using devnet since that was what was (and still is as of today) recommended in the sol-coverage.com docs (BTW you've heard about subdomains right? you don't need to buy a .com for each tool you write).

First of all, the go-ethereum branch used is `0x-testing` which installs some old version. My tests are calling `eth_signTypedData_v3` which wasn't implemented in that version of geth (which is strange, I'm pretty sure you guys must use that method too, since you were the ones who wrote it, basically).

Anyway, I upgraded it to master, rebuilt the docker, etc. It doesn't start, needs `--allow-insecure-unlock`. FFS... Added it, now it starts.

Now my contract fails with "0x1b" unknown opcode. Goddammit the genesis file doesn't have the constantinople fork block number, so I added that and sort of got it working but it's hanging in some weird location.

So while looking into why that is, I notice this comment in `packages/dev-utils/src/blockchain_lifecycle.ts`:

> // HACK(albrow): 🐉 We have to do this so that debug.setHead works correctly.
> // (Geth does not seem to like debug.setHead(0), so by sending some transactions
> // we increase the current block number beyond 0). Additionally, some tests seem
> // to break when there are fewer than 3 blocks in the chain. (We have no idea
> // why, but it was consistently reproducible).

First of all, lol. But second you might want to check your genesis.json file, you are putting byzantiumBlock at 4.

Anyway once I was stuck here I decided to see if any progress had been made with getting coverage to run with ganache, and it looks like it has. So I refactor stuff to use ganache and it works perfectly, and I don't need to fuck around with geth/docker/etc anymore at all, so this whole devnet stuff was a waste of time. Live and learn I guess.

Anyway maybe this brain dump will help somebody else.

**Comment by albrow** [comment]
@hoytech thanks for reaching out. I have been the point person on devnet and can help answer your questions and provide some clarity.

In short, devnet (or at least the version of devnet that uses our fork of Geth) is deprecated and you should use Ganache with our tools moving forward. I'll leave this issue open until we have updated the documentation and sol-coverage.com website to reflect this. Sorry for any trouble this caused you.

For some additional background, we created the devnet package a year ago in order to run our smart contract tests against Geth instead of relying solely on Ganache. To do this, we needed some features from Ganache that are not present in Geth. We created two PRs (see https://github.com/ethereum/go-ethereum/pull/16834, https://github.com/ethereum/go-ethereum/pull/16713, and https://github.com/ethereum/go-ethereum/issues/19346) to implement these features and configured devnet to use our fork while we were waiting for the PRs to be merged upstream. It was working perfectly fine for a while. However, there has been very little response on those PRs so we are now left in a position where our fork is dreadfully out of date.

> First of all, lol. But second you might want to check your genesis.json file, you are putting byzantiumBlock at 4.

You're right. I also caught this mistake and addressed it in https://github.com/0xProject/0x-monorepo/pull/1775. That PR contains our latest attempts to get our Geth fork up to date. It also includes the `--allow-insecure-unlock` flag and many other fixes. It has been extremely difficult to get Geth working and I had to deal with issues unrelated to the features we were trying to add (like a race condition causing `eth_call` to return the wrong results and a broken gas estimator). This difficulty, combined with the general unresponsiveness from the Geth team has caused us to re-evaluate our testing strategy. We have limited development time and have decided it is no longer worth trying to maintain our own fork of Geth.

**Comment by hoytech** [comment]
Thanks! I'm actually very happy about this situation, ganache is a lot faster, works better for changing the time, has better error reporting, and I'm already using it for normal runs of the test-suite.

**Comment by fabioberger** [comment]
Update the docs of all `sol-*` doc pages to suggest using Ganache and removed mention of `devnet`.
