### ISSUE TITLE
Add support for generating subscribe/unsubscribe methods for contract events

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-monorepo#1869]
Currently `abi-gen` does not provide any affordances for devs to subscribe/unsubscribe from contract events in the TS wrappers it generates. We want `abi-gen` to inspect the events emitted by a contract and provide `subscribe`/`unsubscribe` methods to listen to them.

**Comment by xianny** [comment]
Two possible implementations:

1) Combine [`ContractWrapper`](https://github.com/0xProject/0x-monorepo/blob/development/packages/contract-wrappers/src/contract_wrappers/contract_wrapper.ts) into [`BaseContract`](https://github.com/0xProject/0x-monorepo/blob/development/packages/base-contract/src/index.ts) so we can generate [these events-related methods](https://github.com/0xProject/0x-monorepo/blob/development/packages/contract-wrappers/src/contract_wrappers/exchange_wrapper.ts#L1074-L1114) in `abi-gen-wrappers`. Generated wrappers inherit from `BaseContract`. Easy to implement right now, but breaks single responsibility principle. 

2) Use the [official workaround](https://www.typescriptlang.org/docs/handbook/mixins.html) for mixins to inherit both classes. The example provided looks straightforward enough, but I haven't done this before so there is hard-to-estimate risk of running into broken things, especially since these two classes have quite a few injected dependencies.
