### ISSUE TITLE
Order Parameters in isValidSignature function

### ISSUE THREAD

**Issue by GauthamN** [0xProject/0x-monorepo#454]
## Expected Behavior

 In https://github.com/0xProject/0x-monorepo/blob/095388ffe05ca51e92db87ba81d6e4f29b1ab087/packages/contracts/src/contracts/current/protocol/Exchange/MixinSignatureValidator.sol#L135, it would be useful to pass in the order parameters. 

## Current Behavior

isValidSignature function only has hash and signature parameters.

## Possible Solution

Pass order parameters in isValidSignature function and maybe change it's name to isValidOrder to suit the new behaviour. 

## Context

We, at Melonport, have the concept of risk management modules for our funds. A manager can only make an order if certain rules pass as defined by the risk management module (E.g Order price is within 5% of the market price provided by the pricefeed). We consider to implement isValidSignature by checking if the signature belongs the fund manager and the order parameters pass the risk management rules. 

With order parameters, there could be many applications that would find it useful to verify if the order is valid without having to have an on-chain transaction beforehand.

## Your Environment

v2-prototype

**Comment by Recmo** [comment]
Thanks for the feedback!

The `signature` is a dynamic byte array and is intended to contain all the information that the contract needs to verify the signature. This includes the entire `Order` struct if that is required. The example use case can be implemented as:

```
contract FundVerifier is ISigner {

    function isValidSignature(bytes32 hash, bytes signature) public view returns (bool) {
        
        // Unpack bytes
        address fundManager = getAddressFromBytes(signature);
        Order order = getOrderFromBytes(signature);
        
        // Validate
        return 
          hash == getOrderHash(order) &&
          isFundManager(fundManager) &&
          satisfiesRiskProfile(fundManager, order);
    }
}
```

Please note that the function is expected to satisfy the semantics of a signature validator:

* The function can not modify state.
* The function should be pure. 

The pureness requirement is not super strict, but with [ZIP-15](https://github.com/0xProject/ZEIPs/issues/15) a value of `true` will be cached. The order will need to be explicitly canceled when the fund manager changes, or the risk profile no longer allows the order.

Also note that the function can not modify state. You might want to update state to keep track of daily trading volumes.

This part of v2 is definitely not finalized yet, and there are a couple of things we are discussing:

* Including `Order` explicitly as part of the callback. This makes scenarios where a full order struct is required, like yours, easier. It makes the other cases more costly because more data is passed along. It also makes the API less generic. Perhaps we can add two different callback methods.

* Add callbacks for makers that are contracts. `onBeforeFill` `onAfterFill`, etc. These would get all the information and be allowed to modify state.

**Comment by retotrinkler** [comment]
nice thanks v much @Recmo
