### ISSUE TITLE
Web3 typings no longer export used interfaces and types

### ISSUE THREAD

**Issue by ritave** [0xProject/0x-monorepo#530]
Stuff that Web3.EventAbi or Web3.DecodedLogEntry are not exported from web3 typings anymore since they were moved to internal 0xproject types.

This is a bad move due to the @0xproject/types containing internal types too while those moved types are still used in web3 types but are not usable outside while still being returned from functions / required as parameters.

Either move them back, or re-export them in the web3 namespace

**Comment by fabioberger** [comment]
I'd be ok with re-exporting them. Thoughts @LogvinovLeon?

**Comment by LogvinovLeon** [comment]
Yes. We need to re-export them

**Comment by LogvinovLeon** [comment]
I'll work on that

**Comment by LogvinovLeon** [comment]
Those types are returned from web3 public functions, but they're unrelated to web3. They're general ethereum types. I don't think it's possible to re-export them because web3 doesn't use default es6 export. It's just not possible to export anything else than the Web3 object. Before it was working because we used the namespace trick, but you can't export module members from a namespace.

For now - just import those types from `@0xproject/types`;
The fact that it contains other types shouldn't bother you cause types don't contribute to the bundle size.
