### ISSUE TITLE
Is mobile client avaliable not only just using pure javascripts client?

### ISSUE THREAD

**Issue by tantao9323** [0xProject/0x-monorepo#630]
Can we initial a transation from our mobile client? According to the example, we found that we only can start a transation from website or similar situations. That means our private keys are stored in the web site. 

But if we want to realize the system architechture  like mobile clients to initialize and sign the transation for the relayers, seems that would be not possible?

Is there any hit for this requirement or can we found any code snippet for this issue?

**Comment by fabioberger** [comment]
@tantao9323 check out: https://walletconnect.org/. This will allow users to sign txs on mobile, even when using dApp on web.

**Comment by tantao9323** [comment]
@fabioberger thanks for you reply. I means that can we use 0x in native android/iOS application?  not react-native.

**Comment by fabioberger** [comment]
@tantao9323 There are Web3 libraries in Java and Swift that you could use to interact with the 0x smart contracts:
- https://github.com/Boilertalk/Web3.swift
- https://github.com/web3j/web3j

It will be more work then using 0x.js since we did simplify the interface to the smart contracts. 

There is no technical limitation of having txs signed on mobile/web.

**Comment by tantao9323** [comment]
@fabioberger Thank you, we will try it.
