### ISSUE TITLE
[sol-cov] coverage report is incorrect

### ISSUE THREAD

**Issue by perissology** [0xProject/0x-monorepo#703]
## Current Behavior

I haven't investigated too closely, however when I run code coverage, the generated report is incorrect.

As you can see in the img below, line 111 has been covered, but 110 has not. In reality, lines 110 - 115 should all be covered

![screen shot 2018-06-14 at 1 46 52 pm](https://user-images.githubusercontent.com/30963004/41437505-29f233f6-7014-11e8-936f-8e3212bfd40e.png)

## Steps to Reproduce (for bugs)

The above report was generated using the current sol-cov v2-prototype branch with PR #702 [commit here](https://github.com/perissology/0x-monorepo/tree/7a41a5249fcb8457cb8beb823ce9a1362cdbfa98)

you can find instructions to reproduce [here](https://github.com/Giveth/giveth-bridge/issues/4#issuecomment-397425028)

**Comment by LogvinovLeon** [comment]
I'm able to repro that and I'm researching the cause. Thanks for detailed repro instructions

**Comment by LogvinovLeon** [comment]
Ok, got it. We currently don't support creating contracts from within contracts. When we encounter that situation - we just stop parsing that trace and return partial data that we have so far. That's why coverage is broken. I think we should ignore that trace altogether for now. We will properly fix that later when we do support contract creations. I understand that this is a critical use-case for you and you need it. Unfortunately, now we're mostly focused on v2 of the 0x protocol. If you want - you can contribute. I can give you the guidance. Also happy to jump on the call. If you're willing to wait - I hope to get to it in the next 2-3 weeks.
