### ISSUE TITLE
[SoHoAudit] Misleading verbiage within batch processing in batchFillOrders, batchFillOrKillOrders, marketSellOrders, marketSellOrdersNoThrow, marketBuyOrders, marketBuyOrdersNoThrow, and batchCancelOrders

### ISSUE THREAD

**Issue by JonHaas** [0xProject/0x-monorepo#851]
Descriptions within the various batch processing functions reference the synchronous nature of the batch orders and cancellations. As these orders are interfaced with in a for loop, this behavior occurs sequentially and not synchronously.

**Comment by AusIV** [comment]
I think the terminology here is correct.

"Synchronous" implies that when execution of the contract function has completed, all outcomes of the function execution is complete. This would be opposed to "asynchronous," where some future event would complete the task initiated by a call to the function. 

These function calls are synchronous - by the function call returns, there is no further action to complete the call to the function. The only way something might be asynchronous in Solidity is if it depended on an oracle or something, where this function emitted an event and a future function would complete a callback, which is not the case here.

A better term might be "transactionally" rather than "synchronously", as the key point is really that all of the trades in the batch will either complete or none of them will, and you wouldn't end up in a scenario where only half the proposed trades completed.
