### ISSUE TITLE
[SoHoAudit] Usage of block.timestamp within MixinExchangeCore.sol#177 should be avoided for time-sensitive expirations

### ISSUE THREAD

**Issue by JonHaas** [0xProject/0x-monorepo#856]
The usage of `block.timestamp` is generally discouraged due to the level of deviance allowed by block miners. While this deviance is minimal, it should be noted that `block.timestamp` should not be used in time sensitive orders, as abuse of such may lead to order fulfillment of a request that should be expired.

**Comment by abandeali1** [comment]
We had to make the decision to use timestamps vs block numbers for version 1 and decided that we're comfortable with the level of variance allowed by timestamps. Since you don't know when a transaction will be mined, there will always be some level of variance anyways. Traders should always account for these risks when dealing with close to expiration orders.
