### ISSUE TITLE
[sol-cov] coverage report with strange results

### ISSUE THREAD

**Issue by eduadiez** [0xProject/0x-monorepo#956]
## Expected Behavior

I've created a repository with a simple contract (ownable.sol) to test sol-cov and I've found some results that seem not to be correct.

<img width="720" alt="screen shot 2018-08-10 at 15 49 40" src="https://user-images.githubusercontent.com/20141918/43961403-2d6e0a00-9cb5-11e8-9067-8ca151a867bd.png">

It seems very strange that lines 52, 53, 66, 67, 80 and 81 aren't covered. Especially considering that the events are covered.

## Steps to Reproduce (for bugs)
I've created a repository with this contract and the tests to be able to reproduce it: [test_sol-cov](https://github.com/eduadiez/test_sol-cov/tree/master)

**Comment by fabioberger** [comment]
Thanks for the report @eduadiez, we will look into this as soon as possible.

**Comment by LogvinovLeon** [comment]
We know about that issue. The problem lays in a way sol-cov operates. It takes the trace and maps back each opcode executed using source maps. It could happen that the optimizer removed some opcodes as redundant. In that case nothing will map back to that line. It also happens that solidity compiler emits source maps that are not fully correct. Some are arguable.

In order to deal with that we have introduced the means to ignore coverage of some lines. You can use
```
/* solcov ignore next */
```
Before the AST node you know is covered and you want to ignore.

If you want - I can dig deeper into this particular case and look wheather it's the optimizer or the source maps. Let me know
